---

- name: Install K3s on Master Pi
  hosts: master
  become: true
  become_user: root
  tasks:
    - name: Uninstall any existing version of k3s
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

    - name: Install k3s master
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s -
        
    - name: Cat token and register variable
      ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
      register: token 

    - name: Write token to file
      ansible.builtin.copy:
        content: "{{ token.stdout }}"
        dest: ./files/mastertoken.txt
      delegate_to: localhost