---
- name: Install K3s on node(s)
  hosts: nodes
  become: true
  become_user: root
  vars:
    master_token: "{{ lookup('file', './files/mastertoken.txt') }}"
  tasks:
    - name: Install k3s node
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_TOKEN="{{ master_token }}" K3S_URL="https://{{ hostvars['master'].ansible_host }}:6443" K3S_NODE_NAME="{{inventory_hostname}}" sh -
