---
- name: Prep Remote Pi
  hosts: all
  become: true
  become_user: root
  vars:
    ansible_ssh_user: pi
    pi_ssh_password: raspberry
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Reboot the machine
      reboot:
