---
- name: Local Pi Image Prep
  hosts: localhost
  connection: local
  vars:
    path_to_raspian_image: /boot
    netmask: 192.168.1.1
    cmdline_contents: "{{ lookup('file', '{{ path_to_raspian_image }}/cmdline.txt') }}"
  vars_prompt:
    - name: piname
      prompt: Give this device a name
      private: no
    - name: ipaddr
      prompt: Set an ip address for this device
      private: no
  tasks:
    - name: Update cmdline file with ipaddress
      ansible.builtin.lineinfile:
        path: "{{ path_to_raspian_image }}/cmdline.txt"
        regexp: "rootwait"
        line: "{{cmdline_contents}} cgroup_memory=1 cgroup_enable=memory ip={{ ipaddr }}::{{netmask}}:255.255.255.0:{{piname}}:eth0:off"

    - name: Update config file to enable 64bit architecture
      ansible.builtin.lineinfile:
        path: "{{ path_to_raspian_image }}/config.txt"
        line: "arm_64bit=1"
        insertafter:

    - name: Enable ssh by creating ssh file
      shell:
        cmd: touch ssh
        creates: ssh
        chdir: "{{ path_to_raspian_image }}"
        warn: false
